<?php
/**
 * AllotmentApi
 * PHP version 5
 *
 * @category Class
 * @package  HapiRepository
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HAPI Repository API
 *
 * API for retrieving objects from HAPI repository
 *
 * The version of the OpenAPI document: 2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace HapiRepository\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use HapiRepository\ApiException;
use HapiRepository\Configuration;
use HapiRepository\HeaderSelector;
use HapiRepository\ObjectSerializer;

/**
 * AllotmentApi Class Doc Comment
 *
 * @category Class
 * @package  HapiRepository
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AllotmentApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $host_index (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $host_index = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $host_index;
    }

    /**
     * Set the host index
     *
     * @param  int Host index (required)
     */
    public function setHostIndex($host_index)
    {
        $this->hostIndex = $host_index;
    }

    /**
     * Get the host index
     *
     * @return Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getAllotment
     *
     * Get allotments of specified hotel that defined by chainCode / propertyCode (HAPI internal property identifier) and by blockCode and effectiveDate (Allotment external identifier)
     *
     * @param  string $property_code Property code as designated in the PMS (required)
     * @param  string $id Identifier of allotment record in the external system (required)
     *
     * @throws \HapiRepository\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \HapiRepository\Model\Allotment|\HapiRepository\Model\TokenIsInvalidError|\HapiRepository\Model\ObjectNotFoundError
     */
    public function getAllotment($property_code, $id)
    {
        list($response) = $this->getAllotmentWithHttpInfo($property_code, $id);
        return $response;
    }

    /**
     * Operation getAllotmentWithHttpInfo
     *
     * Get allotments of specified hotel that defined by chainCode / propertyCode (HAPI internal property identifier) and by blockCode and effectiveDate (Allotment external identifier)
     *
     * @param  string $property_code Property code as designated in the PMS (required)
     * @param  string $id Identifier of allotment record in the external system (required)
     *
     * @throws \HapiRepository\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \HapiRepository\Model\Allotment|\HapiRepository\Model\TokenIsInvalidError|\HapiRepository\Model\ObjectNotFoundError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAllotmentWithHttpInfo($property_code, $id)
    {
        $request = $this->getAllotmentRequest($property_code, $id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\HapiRepository\Model\Allotment' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\HapiRepository\Model\Allotment', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\HapiRepository\Model\TokenIsInvalidError' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\HapiRepository\Model\TokenIsInvalidError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\HapiRepository\Model\ObjectNotFoundError' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\HapiRepository\Model\ObjectNotFoundError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\HapiRepository\Model\Allotment';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\HapiRepository\Model\Allotment',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\HapiRepository\Model\TokenIsInvalidError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\HapiRepository\Model\ObjectNotFoundError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAllotmentAsync
     *
     * Get allotments of specified hotel that defined by chainCode / propertyCode (HAPI internal property identifier) and by blockCode and effectiveDate (Allotment external identifier)
     *
     * @param  string $property_code Property code as designated in the PMS (required)
     * @param  string $id Identifier of allotment record in the external system (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllotmentAsync($property_code, $id)
    {
        return $this->getAllotmentAsyncWithHttpInfo($property_code, $id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAllotmentAsyncWithHttpInfo
     *
     * Get allotments of specified hotel that defined by chainCode / propertyCode (HAPI internal property identifier) and by blockCode and effectiveDate (Allotment external identifier)
     *
     * @param  string $property_code Property code as designated in the PMS (required)
     * @param  string $id Identifier of allotment record in the external system (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllotmentAsyncWithHttpInfo($property_code, $id)
    {
        $returnType = '\HapiRepository\Model\Allotment';
        $request = $this->getAllotmentRequest($property_code, $id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAllotment'
     *
     * @param  string $property_code Property code as designated in the PMS (required)
     * @param  string $id Identifier of allotment record in the external system (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getAllotmentRequest($property_code, $id)
    {
        // verify the required parameter 'property_code' is set
        if ($property_code === null || (is_array($property_code) && count($property_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $property_code when calling getAllotment'
            );
        }
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getAllotment'
            );
        }

        $resourcePath = '/allotments/{propertyCode}/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($property_code !== null) {
            $resourcePath = str_replace(
                '{' . 'propertyCode' . '}',
                ObjectSerializer::toPathValue($property_code),
                $resourcePath
            );
        }
        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation searchAllotments
     *
     * Search allotments by date range. Paging is included. The maximum number of returned allotments is 1000
     *
     * @param  string $strategy The type of search strategy. Could be range or update. In case of range strategy, records will be searched by their effectiveDate / expireDate instead of searching by updated field in case of update strategy. (required)
     * @param  \HapiRepository\Model\RepositorySearchRequest $repository_search_request repository_search_request (required)
     *
     * @throws \HapiRepository\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \HapiRepository\Model\RecordSet|\HapiRepository\Model\InvalidSearchParametersError|\HapiRepository\Model\TokenIsInvalidError
     */
    public function searchAllotments($strategy, $repository_search_request)
    {
        list($response) = $this->searchAllotmentsWithHttpInfo($strategy, $repository_search_request);
        return $response;
    }

    /**
     * Operation searchAllotmentsWithHttpInfo
     *
     * Search allotments by date range. Paging is included. The maximum number of returned allotments is 1000
     *
     * @param  string $strategy The type of search strategy. Could be range or update. In case of range strategy, records will be searched by their effectiveDate / expireDate instead of searching by updated field in case of update strategy. (required)
     * @param  \HapiRepository\Model\RepositorySearchRequest $repository_search_request (required)
     *
     * @throws \HapiRepository\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \HapiRepository\Model\RecordSet|\HapiRepository\Model\InvalidSearchParametersError|\HapiRepository\Model\TokenIsInvalidError, HTTP status code, HTTP response headers (array of strings)
     */
    public function searchAllotmentsWithHttpInfo($strategy, $repository_search_request)
    {
        $request = $this->searchAllotmentsRequest($strategy, $repository_search_request);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\HapiRepository\Model\RecordSet' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\HapiRepository\Model\RecordSet', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\HapiRepository\Model\InvalidSearchParametersError' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\HapiRepository\Model\InvalidSearchParametersError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\HapiRepository\Model\TokenIsInvalidError' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\HapiRepository\Model\TokenIsInvalidError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\HapiRepository\Model\RecordSet';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\HapiRepository\Model\RecordSet',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\HapiRepository\Model\InvalidSearchParametersError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\HapiRepository\Model\TokenIsInvalidError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation searchAllotmentsAsync
     *
     * Search allotments by date range. Paging is included. The maximum number of returned allotments is 1000
     *
     * @param  string $strategy The type of search strategy. Could be range or update. In case of range strategy, records will be searched by their effectiveDate / expireDate instead of searching by updated field in case of update strategy. (required)
     * @param  \HapiRepository\Model\RepositorySearchRequest $repository_search_request (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchAllotmentsAsync($strategy, $repository_search_request)
    {
        return $this->searchAllotmentsAsyncWithHttpInfo($strategy, $repository_search_request)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchAllotmentsAsyncWithHttpInfo
     *
     * Search allotments by date range. Paging is included. The maximum number of returned allotments is 1000
     *
     * @param  string $strategy The type of search strategy. Could be range or update. In case of range strategy, records will be searched by their effectiveDate / expireDate instead of searching by updated field in case of update strategy. (required)
     * @param  \HapiRepository\Model\RepositorySearchRequest $repository_search_request (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchAllotmentsAsyncWithHttpInfo($strategy, $repository_search_request)
    {
        $returnType = '\HapiRepository\Model\RecordSet';
        $request = $this->searchAllotmentsRequest($strategy, $repository_search_request);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'searchAllotments'
     *
     * @param  string $strategy The type of search strategy. Could be range or update. In case of range strategy, records will be searched by their effectiveDate / expireDate instead of searching by updated field in case of update strategy. (required)
     * @param  \HapiRepository\Model\RepositorySearchRequest $repository_search_request (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function searchAllotmentsRequest($strategy, $repository_search_request)
    {
        // verify the required parameter 'strategy' is set
        if ($strategy === null || (is_array($strategy) && count($strategy) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $strategy when calling searchAllotments'
            );
        }
        // verify the required parameter 'repository_search_request' is set
        if ($repository_search_request === null || (is_array($repository_search_request) && count($repository_search_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $repository_search_request when calling searchAllotments'
            );
        }

        $resourcePath = '/allotments/search/{strategy}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($strategy !== null) {
            $resourcePath = str_replace(
                '{' . 'strategy' . '}',
                ObjectSerializer::toPathValue($strategy),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($repository_search_request)) {
            $_tempBody = $repository_search_request;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
