<?php
/**
 * AllotmentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  HapiRepository
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HAPI Repository API
 *
 * API for retrieving objects from HAPI repository
 *
 * The version of the OpenAPI document: 2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace HapiRepository;

use PHPUnit\Framework\TestCase;

/**
 * AllotmentTest Class Doc Comment
 *
 * @category    Class
 * @description Allotment
 * @package     HapiRepository
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AllotmentTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Allotment"
     */
    public function testAllotment()
    {
    }

    /**
     * Test attribute "property_id"
     */
    public function testPropertyPropertyId()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "block_name"
     */
    public function testPropertyBlockName()
    {
    }

    /**
     * Test attribute "dates"
     */
    public function testPropertyDates()
    {
    }

    /**
     * Test attribute "market_code"
     */
    public function testPropertyMarketCode()
    {
    }

    /**
     * Test attribute "source_code"
     */
    public function testPropertySourceCode()
    {
    }

    /**
     * Test attribute "channel_code"
     */
    public function testPropertyChannelCode()
    {
    }

    /**
     * Test attribute "booking_method"
     */
    public function testPropertyBookingMethod()
    {
    }

    /**
     * Test attribute "billing_type"
     */
    public function testPropertyBillingType()
    {
    }

    /**
     * Test attribute "includes_food_and_bev"
     */
    public function testPropertyIncludesFoodAndBev()
    {
    }

    /**
     * Test attribute "block_type"
     */
    public function testPropertyBlockType()
    {
    }

    /**
     * Test attribute "comments"
     */
    public function testPropertyComments()
    {
    }

    /**
     * Test attribute "profiles"
     */
    public function testPropertyProfiles()
    {
    }

    /**
     * Test attribute "inventory_blocks"
     */
    public function testPropertyInventoryBlocks()
    {
    }

    /**
     * Test attribute "notification_type"
     */
    public function testPropertyNotificationType()
    {
    }

    /**
     * Test attribute "block_inventory_type"
     */
    public function testPropertyBlockInventoryType()
    {
    }

    /**
     * Test attribute "payment_method"
     */
    public function testPropertyPaymentMethod()
    {
    }

    /**
     * Test attribute "repository_created"
     */
    public function testPropertyRepositoryCreated()
    {
    }

    /**
     * Test attribute "repository_updated"
     */
    public function testPropertyRepositoryUpdated()
    {
    }
}
