<?php
/**
 * InventoryBlockTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  HapiRepository
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HAPI Repository API
 *
 * API for retrieving objects from HAPI repository
 *
 * The version of the OpenAPI document: 2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace HapiRepository;

use PHPUnit\Framework\TestCase;

/**
 * InventoryBlockTest Class Doc Comment
 *
 * @category    Class
 * @description InventoryBlock
 * @package     HapiRepository
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InventoryBlockTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InventoryBlock"
     */
    public function testInventoryBlock()
    {
    }

    /**
     * Test attribute "room_type"
     */
    public function testPropertyRoomType()
    {
    }

    /**
     * Test attribute "rate_code"
     */
    public function testPropertyRateCode()
    {
    }

    /**
     * Test attribute "dates"
     */
    public function testPropertyDates()
    {
    }

    /**
     * Test attribute "cutoff_date"
     */
    public function testPropertyCutoffDate()
    {
    }

    /**
     * Test attribute "number_to_block"
     */
    public function testPropertyNumberToBlock()
    {
    }

    /**
     * Test attribute "number_sold"
     */
    public function testPropertyNumberSold()
    {
    }

    /**
     * Test attribute "comp_rooms_number"
     */
    public function testPropertyCompRoomsNumber()
    {
    }

    /**
     * Test attribute "pick_up_status"
     */
    public function testPropertyPickUpStatus()
    {
    }

    /**
     * Test attribute "currency_code"
     */
    public function testPropertyCurrencyCode()
    {
    }

    /**
     * Test attribute "rates"
     */
    public function testPropertyRates()
    {
    }
}
