<?php
/**
 * InventoryBlockTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  HapiRepository
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* HAPI Repository API
 *
* API for retrieving objects from HAPI repository
 *
* OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.4
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace HapiRepository;

/**
 * InventoryBlockTest Class Doc Comment
 *
 * @category    Class
 * @description inventory block detail for allotment
 * @package     HapiRepository
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InventoryBlockTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InventoryBlock"
     */
    public function testInventoryBlock()
    {
    }

    /**
     * Test attribute "room_type"
     */
    public function testPropertyRoomType()
    {
    }

    /**
     * Test attribute "rate_code"
     */
    public function testPropertyRateCode()
    {
    }

    /**
     * Test attribute "dates"
     */
    public function testPropertyDates()
    {
    }

    /**
     * Test attribute "cutoff_date"
     */
    public function testPropertyCutoffDate()
    {
    }

    /**
     * Test attribute "number_to_block"
     */
    public function testPropertyNumberToBlock()
    {
    }

    /**
     * Test attribute "number_sold"
     */
    public function testPropertyNumberSold()
    {
    }

    /**
     * Test attribute "comp_rooms_number"
     */
    public function testPropertyCompRoomsNumber()
    {
    }

    /**
     * Test attribute "pick_up_status"
     */
    public function testPropertyPickUpStatus()
    {
    }

    /**
     * Test attribute "currency_code"
     */
    public function testPropertyCurrencyCode()
    {
    }

    /**
     * Test attribute "rates"
     */
    public function testPropertyRates()
    {
    }
}
