<?php
/**
 * ProfileTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  HapiRepository
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HAPI Repository API
 *
 * API for retrieving objects from HAPI repository
 *
 * The version of the OpenAPI document: 2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace HapiRepository;

use PHPUnit\Framework\TestCase;

/**
 * ProfileTest Class Doc Comment
 *
 * @category    Class
 * @description Profile
 * @package     HapiRepository
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ProfileTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Profile"
     */
    public function testProfile()
    {
    }

    /**
     * Test attribute "property_id"
     */
    public function testPropertyPropertyId()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {
    }

    /**
     * Test attribute "date_of_birth"
     */
    public function testPropertyDateOfBirth()
    {
    }

    /**
     * Test attribute "emails"
     */
    public function testPropertyEmails()
    {
    }

    /**
     * Test attribute "phones"
     */
    public function testPropertyPhones()
    {
    }

    /**
     * Test attribute "addresses"
     */
    public function testPropertyAddresses()
    {
    }

    /**
     * Test attribute "id_documents"
     */
    public function testPropertyIdDocuments()
    {
    }

    /**
     * Test attribute "loyalty_programs"
     */
    public function testPropertyLoyaltyPrograms()
    {
    }

    /**
     * Test attribute "creator"
     */
    public function testPropertyCreator()
    {
    }

    /**
     * Test attribute "created_date"
     */
    public function testPropertyCreatedDate()
    {
    }

    /**
     * Test attribute "travel_agent_id"
     */
    public function testPropertyTravelAgentId()
    {
    }

    /**
     * Test attribute "preferences"
     */
    public function testPropertyPreferences()
    {
    }

    /**
     * Test attribute "comments"
     */
    public function testPropertyComments()
    {
    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {
    }

    /**
     * Test attribute "hapi_id"
     */
    public function testPropertyHapiId()
    {
    }

    /**
     * Test attribute "repository_created"
     */
    public function testPropertyRepositoryCreated()
    {
    }

    /**
     * Test attribute "repository_updated"
     */
    public function testPropertyRepositoryUpdated()
    {
    }
}
