<?php
/**
 * RoomStayTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  HapiRepository
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HAPI Repository API
 *
 * API for retrieving objects from HAPI repository
 *
 * The version of the OpenAPI document: 2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace HapiRepository;

use PHPUnit\Framework\TestCase;

/**
 * RoomStayTest Class Doc Comment
 *
 * @category    Class
 * @description RoomStay
 * @package     HapiRepository
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class RoomStayTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RoomStay"
     */
    public function testRoomStay()
    {
    }

    /**
     * Test attribute "room_number"
     */
    public function testPropertyRoomNumber()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "guest_id"
     */
    public function testPropertyGuestId()
    {
    }

    /**
     * Test attribute "room_type"
     */
    public function testPropertyRoomType()
    {
    }

    /**
     * Test attribute "rate_code"
     */
    public function testPropertyRateCode()
    {
    }

    /**
     * Test attribute "market_code"
     */
    public function testPropertyMarketCode()
    {
    }

    /**
     * Test attribute "channel_code"
     */
    public function testPropertyChannelCode()
    {
    }

    /**
     * Test attribute "source_code"
     */
    public function testPropertySourceCode()
    {
    }

    /**
     * Test attribute "block_code"
     */
    public function testPropertyBlockCode()
    {
    }

    /**
     * Test attribute "room_count"
     */
    public function testPropertyRoomCount()
    {
    }

    /**
     * Test attribute "payment_method"
     */
    public function testPropertyPaymentMethod()
    {
    }

    /**
     * Test attribute "comp_yn"
     */
    public function testPropertyCompYn()
    {
    }

    /**
     * Test attribute "rates"
     */
    public function testPropertyRates()
    {
    }

    /**
     * Test attribute "revenue"
     */
    public function testPropertyRevenue()
    {
    }

    /**
     * Test attribute "services"
     */
    public function testPropertyServices()
    {
    }

    /**
     * Test attribute "promotion_code"
     */
    public function testPropertyPromotionCode()
    {
    }
}
