<?php
/**
 * StayTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Hapi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* HAPI Repository API
 *
* API for retrieving objects from HAPI repository
 *
* OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.4
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Hapi;

/**
 * StayTest Class Doc Comment
 *
 * @category    Class
 * @description Stay
 * @package     Hapi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StayTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Stay"
     */
    public function testStay()
    {
    }

    /**
     * Test attribute "property_id"
     */
    public function testPropertyPropertyId()
    {
    }

    /**
     * Test attribute "reservation_id"
     */
    public function testPropertyReservationId()
    {
    }

    /**
     * Test attribute "room_stay"
     */
    public function testPropertyRoomStay()
    {
    }

    /**
     * Test attribute "repository_created"
     */
    public function testPropertyRepositoryCreated()
    {
    }

    /**
     * Test attribute "repository_updated"
     */
    public function testPropertyRepositoryUpdated()
    {
    }
}
